# Generated by Django 6.0.1 on 2026-04-05 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('max_employees', models.PositiveIntegerField(help_text='Maximum number of volunteer slots', validators=[django.core.validators.MinValueValidator(1)])),
                ('cutoff_date', models.DateTimeField(help_text='Last date/time for employees to register')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seats_taken', models.PositiveIntegerField(default=0)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.ngo')),
            ],
        ),
    ]
