"""
Django settings for csr_enterprise project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9*f9kh@6-ou9euv+=u_*3te6p9p9@jwne5kbj2w*c_$vh&&l8$'

# SECURITY WARNING: don't run with debug turned on in production!
# Topic 7.4.b: Error handling (no sensitive data exposed)
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition
INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'service_dashboard',
    'events',
    'accounts',
    'notifications',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_celery_beat',
]

ROOT_URLCONF = 'csr_enterprise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_notifications',
            ],
        },
    },
]

#WSGI_APPLICATION = 'csr_enterprise.wsgi.application'
# --- TOPIC 10.3: ASGI & CHANNELS CONFIGURATION ---
ASGI_APPLICATION = 'csr_enterprise.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# (Satisfies Topic 6.3 and 6.5.a.i)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Redirect to the homepage (Dashboard) after login
LOGIN_REDIRECT_URL = 'smart_redirect'

# Redirect to the homepage after logout
LOGOUT_REDIRECT_URL = '/'

# Merged and cleaned Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'service_dashboard.middleware.RequestLogMiddleware',  
]

# Merged Jazzmin Settings (AuraIT branding + custom links + logout button)
JAZZMIN_SETTINGS = {
    "site_title": "AuraIT Admin",
    "site_header": "AuraIT Connect",
    "site_brand": "AuraIT Management",
    
    "topmenu_links": [
        {
            "name": " Logout", 
            "url": "admin:logout", 
            "classes": "btn btn-danger text-white fw-bold", 
        }
    ],
    
    "custom_css": "css/admin_tweaks.css",
    "theme": "litera", 
}

# --- NEW: UI Tweaks to fix sidebar spacing ---
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    # This stretches the sidebar just enough to read the words!
    "sidebar_width": 300 
}

# --- ENTERPRISE SECURITY & SESSION MANAGEMENT (TOPIC 6.2 & 6.5) ---

# 1. Session Expiration (Logout user if idle for 30 minutes)
SESSION_COOKIE_AGE = 1800  

# 2. Terminate session immediately when the user closes their browser window
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 3. Security configurations to protect the login session cookie
SESSION_COOKIE_HTTPONLY = True 
SESSION_COOKIE_SAMESITE = 'Lax'

# REST Framework Global Configuration (Topic 8)
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5, # Shows 5 NGOs/Activities per page
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# ==========================================
# ENTERPRISE SECURITY CONFIGURATION (TOPIC 7)
# ==========================================

# Topic 7.1: Apply OWASP Top 10 (CSRF & XSS Protections)
CSRF_COOKIE_HTTPONLY = True 
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Topic 7.2.a: Secure Cookies & Session Management
# Note: In a real production environment with HTTPS, these should be True. 
# We keep them False locally so your login still works on HTTP (127.0.0.1).
SESSION_COOKIE_SECURE = False 
CSRF_COOKIE_SECURE = False   

# Topic 7.2.b: Prevent Session Hijacking (Expiry)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Logs user out if they close the tab
SESSION_COOKIE_AGE = 1800 # Automatically logs user out after 30 minutes of inactivity

# ==========================================
# ENTERPRISE CACHING CONFIGURATION (TOPIC 9.2)
# ==========================================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1', 
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# CELERY SETTINGS (Topic 10.1)
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Print emails to the terminal instead of actually sending them
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'