# Generated by Django 6.0.1 on 2026-02-01 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('max_employees', models.PositiveIntegerField(help_text='Maximum number of volunteer slots')),
                ('cutoff_date', models.DateTimeField(help_text='Last date/time for employees to register')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_dashboard.ngo')),
            ],
            options={
                'unique_together': {('employee', 'ngo')},
            },
        ),
    ]
