# Generated by Django 6.0.1 on 2026-02-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name': 'NGO Event', 'verbose_name_plural': 'NGO Events'},
        ),
    ]
