# Generated by Django 6.0.1 on 2026-03-23 18:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_dashboard', '0002_alter_ngo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={},
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='cutoff_date',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='max_employees',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='start_time',
        ),
        migrations.AddField(
            model_name='ngo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('max_employees', models.PositiveIntegerField(help_text='Maximum number of volunteer slots', validators=[django.core.validators.MinValueValidator(1)])),
                ('cutoff_date', models.DateTimeField(help_text='Last date/time for employees to register')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='service_dashboard.ngo')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registration',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_dashboard.activity'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('employee', 'activity')},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='ngo',
        ),
    ]
