# Generated by Django 6.0.1 on 2026-04-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_dashboard', '0003_alter_ngo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name': 'NGO', 'verbose_name_plural': 'NGOs'},
        ),
    ]
