# Generated by Django 6.0.1 on 2026-04-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(help_text='ID of the User from Port 8001')),
                ('activity_id', models.IntegerField(help_text='ID of the Activity from Port 8002')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('employee_id', 'activity_id')},
            },
        ),
    ]
