# Generated by Django 6.0.1 on 2026-04-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20),
        ),
    ]
